<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Utility\Module'            => __DIR__ . '/Module.php',
  'Utility\Entity\EntityBase' => __DIR__ . '/src/Utility/Entity/EntityBase.php',
  'Utility\Registry'          => __DIR__ . '/src/Utility/Registry.php',
);
