<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Fixture\Module'                       => __DIR__ . '/Module.php',
  'Fixture\Controller\FixtureController' => __DIR__ . '/src/Fixture/Controller/FixtureController.php',
  'Fixture\Service\Fixture'              => __DIR__ . '/src/Fixture/Service/Fixture.php',
);
