<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Profile\Module'         => __DIR__ . '/Module.php',
  'Profile\Entity\Profile' => __DIR__ . '/src/Profile/Entity/Profile.php',
);
