<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'User\Module'                       => __DIR__ . '/Module.php',
    'User\Entity\User'                  => __DIR__ . '/src/User/Entity/User.php',
    'User\Repository\Users'             => __DIR__ . '/src/User/Repository/Users.php',
    'User\Fixture\User'                 => __DIR__ . '/src/User/Fixture/User.php',
    'User\Service\User'                 => __DIR__ . '/src/User/Service/User.php',
    'AuthenticationResponse'            => __DIR__ . '/src/User/Service/User.php',
    'User\Service\UserServiceInterface' => __DIR__ . '/src/User/Service/UserServiceInterface.php',
);
