<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ExchangeOrder\Module'                                => __DIR__ . '/Module.php',
  'ExchangeOrder\DataObject\ExchangeOrder'              => __DIR__ . '/src/ExchangeOrder/DataObject/ExchangeOrder.php',
  'ExchangeOrder\Entity\ExchangeOrder'                  => __DIR__ . '/src/ExchangeOrder/Entity/ExchangeOrder.php',
  'ExchangeOrder\Repository\ExchangeOrders'             => __DIR__ . '/src/ExchangeOrder/Repository/ExchangeOrders.php',
  'ExchangeOrder\Service\ExchangeOrder'                 => __DIR__ . '/src/ExchangeOrder/Service/ExchangeOrder.php',
  'ExchangeOrderResponse'                               => __DIR__ . '/src/ExchangeOrder/Service/ExchangeOrder.php',
  'ExchangeOrder\Service\ExchangeOrderServiceInterface' => __DIR__ . '/src/ExchangeOrder/Service/ExchangeOrderServiceInterface.php',
);
