<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Currency\Entity\Currency'  => __DIR__ . '/src/Currency/Entity/Currency.php',
  'Currency\Fixture\Currency' => __DIR__ . '/src/Currency/Fixture/Currency.php',
);
