<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Currency\Module'                           => __DIR__ . '/Module.php',
    'Currency\Entity\Currency'                  => __DIR__ . '/src/Currency/Entity/Currency.php',
    'Currency\Repository\Currencies'            => __DIR__ . '/src/Currency/Repository/Currencies.php',
    'Currency\Fixture\Currency'                 => __DIR__ . '/src/Currency/Fixture/Currency.php',
    'Currency\Service\Currency'                 => __DIR__ . '/src/Currency/Service/Currency.php',
    'Currency\Service\CurrencyServiceInterface' => __DIR__ . '/src/Currency/Service/CurrencyServiceInterface.php',
);
