<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Order\Module'                        => __DIR__ . '/Module.php',
  'Order\DataObject\Order'              => __DIR__ . '/src/DataObject/Order.php',
  'Order\Entity\Order'                  => __DIR__ . '/src/Entity/Order.php',
  'Order\Repository\Orders'             => __DIR__ . '/src/Repository/Orders.php',
  'Order\Service\Order'                 => __DIR__ . '/src/Service/Order.php',
  'Order\Service\OrderServiceInterface' => __DIR__ . '/src/Service/OrderServiceInterface.php',
);
